runtime: nodejs16

env_variables:
  NODE_ENV: 'production'
  LOG_LEVEL: 'log,warn,error'
  DOMAIN: '.observatoryai.me'
  DATABASE_HOST: '/cloudsql/observatory-344918:northamerica-northeast1:observatory'
  DATABASE_PORT: '5432'
  DATABASE_NAME: 'observatory'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'TrafficLight2022'
  JWT_ACCESS_SECRET: 'fgyuwefbyuiwe'
  JWT_REFRESH_SECRET: 'viuwbuivbweiuvbewiubv'
  SMTP_HOST: 'smtp.gmail.com'
  SMTP_PORT: '465'
  SMTP_SECURE: 'true'
  SMTP_USERNAME: 'observatoryai@gmail.com'
  SMTP_PASSWORD: 'TrafficLight2022'
  GOOGLE_AUTH_CLIENT_ID: '447115811722-a7aqe1kj07qb1lqpj9crdfp5cshi78ho.apps.googleusercontent.com'
  GOOGLE_AUTH_CLIENT_SECRET: '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'

  service: backend
