version: 3
endpoint: http://localhost:8080
admin_secret: admin
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
